name: Pull Request Analysis

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Permite execução manual

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar permissões do Gradle
        run: chmod +x gradlew

      - name: Build do projeto
        run: ./gradlew build

      - name: Rodar testes unitários
        run: ./gradlew test

      - name: Publicar resultados dos testes
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test/
